<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Diagnostics" />
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CollectionInspectorWindow.axaml.cs">
      <DependentUpon>CollectionInspectorWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="ObjectInspectorWindow.axaml.cs">
      <DependentUpon>ObjectInspectorWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
