using System.Xml.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using HandsLiftedApp.Importer.Scripture;

namespace HandsLiftedApp.Tests.Importer.Scripture;

[TestClass]
public class UsxScriptureParserTests
{
    private const string SimpleUsx = """
        <?xml version="1.0" encoding="UTF-8"?>
        <usx version="3.0">
          <book code="GEN" style="id">- Genesis</book>
          <para style="mt1">Genesis</para>
          <chapter number="1" style="c" sid="GEN 1"/>
          <para style="p">
            <verse number="1" style="v" sid="GEN 1:1"/>In the beginning God created the heaven and the earth.<verse eid="GEN 1:1"/>
            <verse number="2" style="v" sid="GEN 1:2"/>And the earth was without form, and void.<verse eid="GEN 1:2"/>
          </para>
          <chapter eid="GEN 1"/>
        </usx>
        """;

    // Mirrors the real shape fetched from v1.fetch.bible/bibles/eng_bsb/usx/gen.usx:
    // book element holds a generator credit (not the title), a section heading (s2) that
    // must be skipped, a footnote on verse 3, and verse 5 + verse 27's text split across
    // multiple <para> elements via the `vid` continuation attribute.
    private const string BsbShapedUsx = """
        <?xml version="1.0" encoding="utf-8"?>
        <usx version="3.0">
          <book code="GEN" style="id">Autogenerated BSB by bsb2usfm</book>
          <para style="mt1">Genesis</para>
          <chapter number="1" style="c" sid="GEN 1" />
          <para style="s2">The First Day</para>
          <para style="p">
            <verse number="3" style="v" sid="GEN 1:3" />And God said, &#8220;Let there be light,&#8221;<note caller="+" style="f"><char style="fr" closed="false">1:3 </char><char style="ft" closed="false">Cited in 2 Corinthians 4:6</char></note> and there was light. <verse eid="GEN 1:3" /><verse number="4" style="v" sid="GEN 1:4" />And God saw that the light was good.<verse eid="GEN 1:4" /><verse number="5" style="v" sid="GEN 1:5" />God called the light &#8220;day,&#8221; and the darkness He called &#8220;night.&#8221;</para>
          <para style="p" vid="GEN 1:5">And there was evening, and there was morning — the first day.<verse eid="GEN 1:5" /></para>
          <para style="b" />
          <para style="q1">
            <verse number="27" style="v" sid="GEN 1:27" />So God created man in His own image;</para>
          <para style="q2" vid="GEN 1:27">in the image of God He created him;</para>
          <para style="q2" vid="GEN 1:27">male and female He created them.<verse eid="GEN 1:27" /></para>
          <chapter eid="GEN 1" />
        </usx>
        """;

    [TestMethod]
    public void Parse_SimpleUsx_ReturnsBookCodeAndTitle()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(SimpleUsx));

        Assert.AreEqual("GEN", book.Code);
        Assert.AreEqual("Genesis", book.Title);
    }

    [TestMethod]
    public void Parse_SimpleUsx_GroupsBothVersesIntoOneParagraph()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(SimpleUsx));

        Assert.AreEqual(1, book.Paragraphs.Count);
        var paragraph = book.Paragraphs[0];
        Assert.AreEqual(1, paragraph.StartChapter);
        Assert.IsFalse(paragraph.IsPoetry);
        Assert.AreEqual(2, paragraph.Verses.Count);
        Assert.AreEqual(1, paragraph.Verses[0].VerseNumber);
        Assert.AreEqual("In the beginning God created the heaven and the earth.", paragraph.Verses[0].Text);
        Assert.AreEqual(2, paragraph.Verses[1].VerseNumber);
        Assert.AreEqual("And the earth was without form, and void.", paragraph.Verses[1].Text);
    }

    [TestMethod]
    public void Parse_BsbShapedUsx_PrefersMt1TitleOverBookElementText()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        Assert.AreEqual("GEN", book.Code);
        Assert.AreEqual("Genesis", book.Title);
    }

    [TestMethod]
    public void Parse_BsbShapedUsx_SkipsSectionHeadingAndEmptyParagraph()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        // 5 kept paragraphs: [v3-5a], [v5b continuation], [v27a q1], [v27b q2], [v27c q2].
        // "The First Day" (s2) and the empty <para style="b" /> must not appear.
        Assert.AreEqual(5, book.Paragraphs.Count);
        foreach (var paragraph in book.Paragraphs)
        {
            Assert.IsTrue(paragraph.Verses.Count > 0);
        }
    }

    [TestMethod]
    public void Parse_BsbShapedUsx_CapturesFootnoteOnVerseThree()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var firstParagraph = book.Paragraphs[0];
        Assert.AreEqual(3, firstParagraph.Verses[0].VerseNumber);
        Assert.AreEqual(1, firstParagraph.Verses[0].Footnotes.Count);
        Assert.AreEqual("Cited in 2 Corinthians 4:6", firstParagraph.Verses[0].Footnotes[0].Text);
    }

    [TestMethod]
    public void Parse_BsbShapedUsx_SplitsVerseFiveTextAcrossTwoParagraphs()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var firstParagraph = book.Paragraphs[0];
        Assert.AreEqual(5, firstParagraph.Verses[2].VerseNumber);
        Assert.AreEqual("God called the light “day,” and the darkness He called “night.”", firstParagraph.Verses[2].Text);

        var continuationParagraph = book.Paragraphs[1];
        Assert.AreEqual(1, continuationParagraph.Verses.Count);
        Assert.AreEqual(5, continuationParagraph.Verses[0].VerseNumber);
        Assert.AreEqual("And there was evening, and there was morning — the first day.", continuationParagraph.Verses[0].Text);
    }

    [TestMethod]
    public void Parse_BsbShapedUsx_TracksPoetryAcrossContinuationParagraphs()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var q1Paragraph = book.Paragraphs[2];
        Assert.IsTrue(q1Paragraph.IsPoetry);
        Assert.AreEqual(1, q1Paragraph.PoetryIndentLevel);
        Assert.AreEqual(27, q1Paragraph.Verses[0].VerseNumber);
        Assert.AreEqual("So God created man in His own image;", q1Paragraph.Verses[0].Text);

        var q2ParagraphA = book.Paragraphs[3];
        Assert.AreEqual(2, q2ParagraphA.PoetryIndentLevel);
        Assert.AreEqual(27, q2ParagraphA.Verses[0].VerseNumber);
        Assert.AreEqual("in the image of God He created him;", q2ParagraphA.Verses[0].Text);

        var q2ParagraphB = book.Paragraphs[4];
        Assert.AreEqual(27, q2ParagraphB.Verses[0].VerseNumber);
        Assert.AreEqual("male and female He created them.", q2ParagraphB.Verses[0].Text);
    }
}
