using System.Xml.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using HandsLiftedApp.Importer.Scripture;
using HandsLiftedApp.Core.Models.RuntimeData.Items;

namespace HandsLiftedApp.Tests.Models.RuntimeData.Items;

[TestClass]
public class ScriptureVerseRangeExtractorTests
{
    // Same fixture as Phase 1's UsxScriptureParserTests.BsbShapedUsx — kept in sync
    // deliberately so this test exercises the exact same split-verse shapes.
    private const string BsbShapedUsx = """
        <?xml version="1.0" encoding="utf-8"?>
        <usx version="3.0">
          <book code="GEN" style="id">Autogenerated BSB by bsb2usfm</book>
          <para style="mt1">Genesis</para>
          <chapter number="1" style="c" sid="GEN 1" />
          <para style="s2">The First Day</para>
          <para style="p">
            <verse number="3" style="v" sid="GEN 1:3" />And God said, &#8220;Let there be light,&#8221;<note caller="+" style="f"><char style="fr" closed="false">1:3 </char><char style="ft" closed="false">Cited in 2 Corinthians 4:6</char></note> and there was light. <verse eid="GEN 1:3" /><verse number="4" style="v" sid="GEN 1:4" />And God saw that the light was good.<verse eid="GEN 1:4" /><verse number="5" style="v" sid="GEN 1:5" />God called the light &#8220;day,&#8221; and the darkness He called &#8220;night.&#8221;</para>
          <para style="p" vid="GEN 1:5">And there was evening, and there was morning — the first day.<verse eid="GEN 1:5" /></para>
          <para style="b" />
          <para style="q1">
            <verse number="27" style="v" sid="GEN 1:27" />So God created man in His own image;</para>
          <para style="q2" vid="GEN 1:27">in the image of God He created him;</para>
          <para style="q2" vid="GEN 1:27">male and female He created them.<verse eid="GEN 1:27" /></para>
          <chapter number="2" style="c" sid="GEN 2" />
          <para style="p">
            <verse number="1" style="v" sid="GEN 2:1" />Thus the heavens and the earth were completed.<verse eid="GEN 2:1" /></para>
          <chapter eid="GEN 2" />
        </usx>
        """;

    [TestMethod]
    public void Extract_FullRange_MergesVerseFiveSplitAcrossParagraphs()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var verses = ScriptureVerseRangeExtractor.Extract(book, startChapter: 1, startVerse: 3, endChapter: 1, endVerse: 5);

        Assert.AreEqual(3, verses.Count);
        Assert.AreEqual(5, verses[2].Verse);
        Assert.AreEqual(1, verses[2].Chapter);
        Assert.AreEqual(
            "God called the light “day,” and the darkness He called “night.” And there was evening, and there was morning — the first day.",
            verses[2].Text);
    }

    [TestMethod]
    public void Extract_FullRange_MergesVerseTwentySevenSplitAcrossThreeParagraphs()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var verses = ScriptureVerseRangeExtractor.Extract(book, startChapter: 1, startVerse: 27, endChapter: 1, endVerse: 27);

        Assert.AreEqual(1, verses.Count);
        Assert.AreEqual(27, verses[0].Verse);
        Assert.AreEqual(
            "So God created man in His own image; in the image of God He created him; male and female He created them.",
            verses[0].Text);
    }

    [TestMethod]
    public void Extract_RangeExcludingVerseFive_StopsAtVerseFour()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var verses = ScriptureVerseRangeExtractor.Extract(book, startChapter: 1, startVerse: 3, endChapter: 1, endVerse: 4);

        Assert.AreEqual(2, verses.Count);
        Assert.AreEqual(4, verses[1].Verse);
    }

    [TestMethod]
    public void Extract_RangeSpanningChapters_IncludesBothChapters()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var verses = ScriptureVerseRangeExtractor.Extract(book, startChapter: 1, startVerse: 27, endChapter: 2, endVerse: 1);

        Assert.AreEqual(2, verses.Count);
        Assert.AreEqual(1, verses[0].Chapter);
        Assert.AreEqual(27, verses[0].Verse);
        Assert.AreEqual(2, verses[1].Chapter);
        Assert.AreEqual(1, verses[1].Verse);
        Assert.AreEqual("Thus the heavens and the earth were completed.", verses[1].Text);
    }

    [TestMethod]
    public void Extract_EmptyRange_ReturnsEmptyList()
    {
        var book = UsxScriptureParser.Parse(XDocument.Parse(BsbShapedUsx));

        var verses = ScriptureVerseRangeExtractor.Extract(book, startChapter: 1, startVerse: 100, endChapter: 1, endVerse: 200);

        Assert.AreEqual(0, verses.Count);
    }
}
